# ============================================================
#  Auto3Tier — the only file you need to edit
# ============================================================

project_name = "myapp"
aws_region   = "eu-west-1"

# --- Your backend -------------------------------------------
# Full ECR image URI including the tag.
backend_image = "123456789012.dkr.ecr.eu-west-1.amazonaws.com/api:v1"

# Port your container listens on, and a path that returns 200
# without authentication. If the health check fails, the
# deployment rolls back.
backend_port = 8080
health_path  = "/health"

# Must match the image you pushed. Images built on an Apple
# Silicon Mac without --platform linux/amd64 are ARM64.
cpu_architecture = "X86_64"

# 256 CPU units = 0.25 vCPU. Valid memory values depend on cpu.
cpu           = 256
memory        = 512
desired_count = 1

# --- Your frontend ------------------------------------------
# Put your built SPA in spa/ — the contents of dist/ or build/,
# so that spa/index.html exists. Nothing to configure here.

# NA + Europe. PriceClass_200 adds Asia/ME/Africa, PriceClass_All
# adds South America and Oceania. Does not restrict who can access.
price_class = "PriceClass_100"

# --- Database -----------------------------------------------
# The password is generated by RDS and stored in Secrets Manager.
# It is never written to Terraform state.
db_name     = "appdb"
db_username = "appuser"

db_instance_class    = "db.t4g.micro"
db_allocated_storage = 20

# Standby in a second AZ. Roughly doubles database cost.
db_multi_az = false

# --- Network ------------------------------------------------
vpc_cidr = "10.0.0.0/16"
az_count = 2

# NAT gives the private subnets outbound internet access, which is how
# ECS pulls your image from ECR. Turning it off will stop tasks from
# starting unless you add VPC endpoints yourself.
enable_nat_gateway = true

# One shared NAT gateway saves ~$32/month. One AZ failure then
# takes out egress for all private subnets. Set false for production.
single_nat_gateway = true

tags = {
  ManagedBy = "terraform"
}
