variable "aws_region" {
  description = "Region for all infrastructure. Cannot be changed after the first deploy without destroying first."
  type        = string
  default     = "eu-west-1"
}

variable "project_name" {
  description = "Prefix for all resource names. Lowercase letters, digits and hyphens only."
  type        = string
  default     = "myapp"

  # ALB and target group names cap at 32 chars and reject underscores.
  # 21 leaves room for the longest suffix appended ("-ecs-execution").
  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{0,20}$", var.project_name))
    error_message = "project_name must start with a lowercase letter, contain only lowercase letters, digits and hyphens, and be at most 21 characters."
  }
}

# --- Backend ---------------------------------------------------------------

variable "backend_image" {
  description = "Full ECR image URI including tag, e.g. 123456789012.dkr.ecr.eu-west-1.amazonaws.com/api:v1"
  type        = string
}

variable "backend_port" {
  description = "Port your container listens on"
  type        = number
  default     = 8080
}

variable "health_path" {
  description = "Path the load balancer polls. Must return 200 without authentication."
  type        = string
  default     = "/health"
}

variable "cpu_architecture" {
  description = "X86_64 or ARM64. Must match the image you pushed — images built on Apple Silicon without --platform are ARM64."
  type        = string
  default     = "X86_64"
}

variable "cpu" {
  description = "Task CPU units: 256, 512, 1024, 2048 or 4096"
  type        = number
  default     = 256
}

variable "memory" {
  description = "Task memory in MiB. Must be a valid pairing with cpu — see modules/application-tier/variables.tf."
  type        = number
  default     = 512
}

variable "desired_count" {
  description = "How many copies of the backend to run"
  type        = number
  default     = 1
}

# --- Database --------------------------------------------------------------

variable "db_name" {
  description = "Initial database name"
  type        = string
  default     = "appdb"
}

variable "db_username" {
  description = "Master username. The password is generated by RDS and stored in Secrets Manager."
  type        = string
  default     = "appuser"
}

variable "db_instance_class" {
  description = "RDS instance size. db.t4g.micro is Graviton and cheapest; use db.t3.micro if t4g is unavailable in your region."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage" {
  description = "Initial storage in GB. Grows automatically up to the module's maximum."
  type        = number
  default     = 20
}

variable "db_multi_az" {
  description = "Run a standby in a second AZ. Roughly doubles database cost."
  type        = bool
  default     = false
}

# --- Frontend --------------------------------------------------------------

variable "price_class" {
  description = "CloudFront edge coverage: PriceClass_100 (NA + Europe), PriceClass_200 (adds Asia/ME/Africa), PriceClass_All."
  type        = string
  default     = "PriceClass_100"
}

# --- Network ---------------------------------------------------------------

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "az_count" {
  description = "Number of AZs to spread across"
  type        = number
  default     = 2

  # RDS needs two AZs; three tiers out of 16 /20 blocks caps it at five.
  validation {
    condition     = var.az_count >= 2 && var.az_count <= 5
    error_message = "az_count must be between 2 and 5. RDS requires at least two AZs."
  }
}

variable "enable_nat_gateway" {
  description = "Give private subnets outbound internet access. Required for ECR image pulls — turning this off will stop tasks from starting."
  type        = bool
  default     = true
}

variable "single_nat_gateway" {
  description = "Share one NAT gateway across AZs. Saves roughly $32/month; one AZ failure takes out egress for all private subnets."
  type        = bool
  default     = true
}

variable "tags" {
  description = "Tags applied to every resource"
  type        = map(string)
  default     = {}
}
