variable "name" {
  description = "Prefix for all resource names"
  type        = string
}

variable "tags" {
  description = "Tags applied to every resource"
  type        = map(string)
  default     = {}
}

variable "vpc_id" {
  description = "VPC the database security group belongs to"
  type        = string
}

variable "subnet_ids" {
  description = "Isolated data-tier subnets. RDS requires at least two, in different AZs, even when multi_az is false."
  type        = list(string)
}

variable "db_name" {
  description = "Name of the initial database created inside the instance"
  type        = string
}

variable "db_username" {
  description = "Master username. The password is generated by RDS and stored in Secrets Manager, never in Terraform state."
  type        = string
}

variable "engine_version" {
  description = "PostgreSQL major version. RDS resolves it to the latest matching minor release."
  type        = string
  default     = "16"
}

variable "instance_class" {
  description = "RDS instance size. t4g is Graviton and cheapest; fall back to db.t3.micro where t4g is unavailable."
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  description = "Initial storage in GB"
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Ceiling for storage autoscaling. Set equal to allocated_storage to disable growth."
  type        = number
  default     = 100
}

variable "multi_az" {
  description = "Run a synchronous standby in a second AZ. Roughly doubles cost; survives an AZ failure."
  type        = bool
  default     = false
}
